### Not Found Exception

Вы развиваете приложение с менеджером товаров, который мы рассматривали на лекции, и решили сделать так, чтобы при попытке удаления несуществующего объекта 
из репозитория генерировалось ваше исключение, а не *ArrayIndexOfBoundsException*.

Обратите внимание: это правильный подход, поскольку таким образом вы сообщаете (через генерацию исключения), что это исключение, вписывающееся в вашу логику, а не является ошибкой программиста.

Что нужно сделать:

1. Возьмите проект (мы его писали в рамках дз про наследование) с менеджером, репозиторием и товарами.

2. Создайте класс исключения NotFoundException отнаследовавшись от RuntimeException и реализуйте как минимум конструктор с параметром-сообщением (он будет просто вызывать супер-конструктор предка, см. подсказку).

3. В методе удаления removeById сначала проверяйте, есть ли элемент (для этого прямо из метода removeById вызывайте метод findById (про него ниже): если результат - null, тогда выкидывайте исключение NotFoundException).

4. Напишите 2 автотеста на репозиторий: первый должен проверять успешность удаления существующего элемента, второй - генерации NotFoundException при попытке удаления несуществующего элемента.



**Итого:** у вас должен быть репозиторий на GitHub, в котором расположен ваш Java-код и автотесты к нему.

Мы рекомендуем вам указывать в сообщении исключения: при удалении по какому конкретно id было сгенерировано ваше исключение. Сделать это можно следующим образом (простейший способ): "Element with id: " + id + " not found".

